name: ejercicios
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/logo.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/fontelico.ttf
    - assets/screens1/imagen_representativa.jpg
    - assets/screens3/lirios.webp
    - assets/screens3/radiata.jpg
    - assets/screens3/rosas.jpg
    - assets/screens5/libro1.jpg
    - assets/screens5/libro2.jpg
    - assets/screens5/libro3.jpg
    - assets/screens5/libro4.jpg
    - assets/screens5/libro5.jpg
    - assets/screens7/album1.jpg
    - assets/img/banner.jpg
    - assets/img/logoAnimado.gif
    - assets/screens11/fotoPerfil.jpg
    - assets/screens11/destacadas/animales.jpg
    - assets/screens11/destacadas/autofoto.jpg
    - assets/screens11/destacadas/comida.jpg
    - assets/screens11/destacadas/humanos.jpg
    - assets/screens11/destacadas/paseo.jpg
    - assets/screens11/iconos/comprar.png
    - assets/screens11/iconos/etiquetado.png
    - assets/screens11/iconos/publicacion.png
    - assets/screens11/iconos/reels.png
    - assets/screens11/fotos/foto1.jpg
    - assets/screens11/fotos/foto2.jpg
    - assets/screens11/fotos/foto3.jpg
    - assets/screens11/fotos/foto4.jpg
    - assets/screens11/fotos/foto5.jpg
    - assets/screens11/fotos/foto6.jpg
    - assets/screens11/fotos/foto7.jpg
    - assets/screens11/fotos/foto8.jpeg
    - assets/screens11/fotos/foto9.jpeg
    - assets/screens11/fotos/foto10.jpg
    - assets/screens13/img1.jpg
    - assets/screens13/img2.jpg
    - assets/screens13/img3.jpg
    - assets/screens13/img4.jpg
    - assets/screens13/img5.jpg
    - assets/screens14/foto.jpg

  fonts:
    - family: Fontelico
      fonts:
        - asset: assets/fonts/fontelico.ttf